
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leats
 */
public class GuestPanel extends javax.swing.JFrame {

    /**
     * Creates new form GuestPanel
     */
    
    CardLayout cards;
    public GuestPanel() {
        setIconImage(new ImageIcon("src\\res\\patient.png").getImage());
        initComponents();
        cards = (CardLayout)(PanelContainer.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        NotFoundPopUp = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        notfoundButton = new javax.swing.JButton();
        Toolbar = new javax.swing.JPanel();
        ToolBarButtons = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        SearchPatientRecordButton = new MyButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        PrintButton = new MyButton();
        LogOutButton = new javax.swing.JPanel();
        LogOut = new MyButton();
        PanelContainer = new javax.swing.JPanel();
        MainScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchRecordByNamePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        SearchByNameLabel = new javax.swing.JLabel();
        SearchByNameField = new javax.swing.JTextField();
        SearchPatientByNameButton = new MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchByNameTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SearchRecordByIDPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        SearchRecordByIDLabel = new javax.swing.JLabel();
        SearchByIDField = new javax.swing.JTextField();
        SearchRecordByIDButton = new MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchRecordByIDTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SearchRecordByAgePanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        SearchRecordByAgeLabel = new javax.swing.JLabel();
        SearchByAgeField = new javax.swing.JTextField();
        SearchRecordByAgeButton = new MyButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        SearchRecordByAgeTable = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        SearchRecord = new javax.swing.JMenu();
        SearchPatientbyName = new javax.swing.JMenuItem();
        SearchPatientbyID = new javax.swing.JMenuItem();
        SearchPatientbyAge = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        AboutUs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ChangePassword = new javax.swing.JMenuItem();

        NotFoundPopUp.setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/not-found.png"))); // NOI18N
        jPanel7.add(jLabel13, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Record Not Found");
        jPanel8.add(jLabel14, new java.awt.GridBagConstraints());

        notfoundButton.setText("OK");
        notfoundButton.setPreferredSize(new java.awt.Dimension(55, 30));
        notfoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notfoundButtonActionPerformed(evt);
            }
        });
        notfoundButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                notfoundButtonKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(33, 0, 0, 9);
        jPanel8.add(notfoundButton, gridBagConstraints);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        NotFoundPopUp.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 660));

        Toolbar.setLayout(new java.awt.BorderLayout());

        ToolBarButtons.setBackground(new java.awt.Color(238, 236, 236));
        ToolBarButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        ToolBarButtons.add(jSeparator5);

        SearchPatientRecordButton.setBackground(new java.awt.Color(238, 236, 236));
        SearchPatientRecordButton.setBorder(null);
        SearchPatientRecordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/searchnewrecord.png"))); // NOI18N
        SearchPatientRecordButton.setBorderColor(new java.awt.Color(240, 240, 240));
        SearchPatientRecordButton.setColor(new java.awt.Color(238, 236, 236));
        SearchPatientRecordButton.setColorClick(new java.awt.Color(204, 204, 255));
        SearchPatientRecordButton.setColorOver(new java.awt.Color(153, 153, 255));
        SearchPatientRecordButton.setFocusable(false);
        SearchPatientRecordButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchPatientRecordButton.setPreferredSize(new java.awt.Dimension(40, 40));
        SearchPatientRecordButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SearchPatientRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientRecordButtonActionPerformed(evt);
            }
        });
        ToolBarButtons.add(SearchPatientRecordButton);
        ToolBarButtons.add(jSeparator6);
        ToolBarButtons.add(jSeparator7);

        PrintButton.setBackground(new java.awt.Color(238, 236, 236));
        PrintButton.setBorder(null);
        PrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/print.png"))); // NOI18N
        PrintButton.setBorderColor(new java.awt.Color(240, 240, 240));
        PrintButton.setColor(new java.awt.Color(238, 236, 236));
        PrintButton.setColorClick(new java.awt.Color(204, 204, 255));
        PrintButton.setColorOver(new java.awt.Color(153, 153, 255));
        PrintButton.setFocusable(false);
        PrintButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PrintButton.setPreferredSize(new java.awt.Dimension(40, 40));
        PrintButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBarButtons.add(PrintButton);

        Toolbar.add(ToolBarButtons, java.awt.BorderLayout.CENTER);

        LogOutButton.setBackground(new java.awt.Color(238, 236, 236));
        LogOutButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        LogOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Logout.png"))); // NOI18N
        LogOut.setBorderColor(new java.awt.Color(255, 102, 102));
        LogOut.setColor(new java.awt.Color(255, 153, 153));
        LogOut.setColorClick(new java.awt.Color(204, 204, 255));
        LogOut.setColorOver(new java.awt.Color(255, 102, 102));
        LogOut.setFocusable(false);
        LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut.setPreferredSize(new java.awt.Dimension(40, 40));
        LogOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LogOutButton.add(LogOut);

        Toolbar.add(LogOutButton, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Toolbar, java.awt.BorderLayout.PAGE_START);

        PanelContainer.setBackground(new java.awt.Color(204, 204, 255));
        PanelContainer.setLayout(new java.awt.CardLayout());

        MainScreen.setBackground(new java.awt.Color(255, 255, 255));
        MainScreen.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/StartScreen.png"))); // NOI18N
        MainScreen.add(jLabel1, new java.awt.GridBagConstraints());

        PanelContainer.add(MainScreen, "card1");

        SearchRecordByNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        SearchRecordByNamePanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        SearchByNameLabel.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        SearchByNameLabel.setText("Enter Patient Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 18, 0);
        jPanel4.add(SearchByNameLabel, gridBagConstraints);

        SearchByNameField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        SearchByNameField.setPreferredSize(new java.awt.Dimension(200, 35));
        SearchByNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(21, 20, 18, 0);
        jPanel4.add(SearchByNameField, gridBagConstraints);

        SearchPatientByNameButton.setBackground(new java.awt.Color(204, 204, 255));
        SearchPatientByNameButton.setText("Search");
        SearchPatientByNameButton.setBorderColor(new java.awt.Color(153, 153, 153));
        SearchPatientByNameButton.setColor(new java.awt.Color(204, 204, 255));
        SearchPatientByNameButton.setColorClick(new java.awt.Color(129, 117, 249));
        SearchPatientByNameButton.setColorOver(new java.awt.Color(153, 153, 255));
        SearchPatientByNameButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchPatientByNameButton.setPreferredSize(new java.awt.Dimension(80, 30));
        SearchPatientByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientByNameButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 29, 0, 0);
        jPanel4.add(SearchPatientByNameButton, gridBagConstraints);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        SearchByNameTable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        SearchByNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "PF_Name", "Gender", "DOB", "Doctor_ID", "Disease History", "Prescription"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchByNameTable.setRowSelectionAllowed(false);
        SearchByNameTable.setShowGrid(false);
        SearchByNameTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(SearchByNameTable);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        SearchRecordByNamePanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Search.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jLabel11, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel9.setText("Search Record");
        jPanel5.add(jLabel9, new java.awt.GridBagConstraints());

        SearchRecordByNamePanel.add(jPanel5, java.awt.BorderLayout.LINE_START);

        PanelContainer.add(SearchRecordByNamePanel, "card2");

        SearchRecordByIDPanel.setBackground(new java.awt.Color(255, 255, 255));
        SearchRecordByIDPanel.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        SearchRecordByIDLabel.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        SearchRecordByIDLabel.setText("Enter Patient ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 18, 0);
        jPanel9.add(SearchRecordByIDLabel, gridBagConstraints);

        SearchByIDField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        SearchByIDField.setPreferredSize(new java.awt.Dimension(200, 35));
        SearchByIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByIDFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(21, 20, 18, 0);
        jPanel9.add(SearchByIDField, gridBagConstraints);

        SearchRecordByIDButton.setBackground(new java.awt.Color(204, 204, 255));
        SearchRecordByIDButton.setText("Search");
        SearchRecordByIDButton.setBorderColor(new java.awt.Color(153, 153, 153));
        SearchRecordByIDButton.setColor(new java.awt.Color(204, 204, 255));
        SearchRecordByIDButton.setColorClick(new java.awt.Color(129, 117, 249));
        SearchRecordByIDButton.setColorOver(new java.awt.Color(153, 153, 255));
        SearchRecordByIDButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchRecordByIDButton.setPreferredSize(new java.awt.Dimension(80, 30));
        SearchRecordByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRecordByIDButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 29, 0, 0);
        jPanel9.add(SearchRecordByIDButton, gridBagConstraints);

        jPanel6.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        SearchRecordByIDTable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        SearchRecordByIDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "PF_Name", "Gender", "DOB", "Doctor_ID", "Disease History", "Prescription"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchRecordByIDTable.setRowSelectionAllowed(false);
        SearchRecordByIDTable.setShowGrid(false);
        SearchRecordByIDTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(SearchRecordByIDTable);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        SearchRecordByIDPanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Search.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel10.add(jLabel12, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel10.setText("Search Record");
        jPanel10.add(jLabel10, new java.awt.GridBagConstraints());

        SearchRecordByIDPanel.add(jPanel10, java.awt.BorderLayout.LINE_START);

        PanelContainer.add(SearchRecordByIDPanel, "card3");

        SearchRecordByAgePanel.setBackground(new java.awt.Color(255, 255, 255));
        SearchRecordByAgePanel.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        SearchRecordByAgeLabel.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        SearchRecordByAgeLabel.setText("Enter Patient Age:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 18, 0);
        jPanel12.add(SearchRecordByAgeLabel, gridBagConstraints);

        SearchByAgeField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        SearchByAgeField.setPreferredSize(new java.awt.Dimension(200, 35));
        SearchByAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByAgeFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(21, 20, 18, 0);
        jPanel12.add(SearchByAgeField, gridBagConstraints);

        SearchRecordByAgeButton.setBackground(new java.awt.Color(204, 204, 255));
        SearchRecordByAgeButton.setText("Search");
        SearchRecordByAgeButton.setBorderColor(new java.awt.Color(153, 153, 153));
        SearchRecordByAgeButton.setColor(new java.awt.Color(204, 204, 255));
        SearchRecordByAgeButton.setColorClick(new java.awt.Color(129, 117, 249));
        SearchRecordByAgeButton.setColorOver(new java.awt.Color(153, 153, 255));
        SearchRecordByAgeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchRecordByAgeButton.setPreferredSize(new java.awt.Dimension(80, 30));
        SearchRecordByAgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRecordByAgeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 29, 0, 0);
        jPanel12.add(SearchRecordByAgeButton, gridBagConstraints);

        jPanel11.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        SearchRecordByAgeTable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        SearchRecordByAgeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "PF_Name", "Gender", "DOB", "Doctor_ID", "Disease History", "Prescription"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchRecordByAgeTable.setRowSelectionAllowed(false);
        SearchRecordByAgeTable.setShowGrid(false);
        SearchRecordByAgeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(SearchRecordByAgeTable);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        SearchRecordByAgePanel.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Search.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel13.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel16.setText("Search Record");
        jPanel13.add(jLabel16, new java.awt.GridBagConstraints());

        SearchRecordByAgePanel.add(jPanel13, java.awt.BorderLayout.LINE_START);

        PanelContainer.add(SearchRecordByAgePanel, "card4");

        getContentPane().add(PanelContainer, java.awt.BorderLayout.CENTER);

        jMenuBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SearchRecord.setText("Search Record");

        SearchPatientbyName.setText("Search Patient by Name");
        SearchPatientbyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientbyNameActionPerformed(evt);
            }
        });
        SearchRecord.add(SearchPatientbyName);

        SearchPatientbyID.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SearchPatientbyID.setText("Search Patient by ID");
        SearchPatientbyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientbyIDActionPerformed(evt);
            }
        });
        SearchRecord.add(SearchPatientbyID);

        SearchPatientbyAge.setText("Search Patient by Age");
        SearchPatientbyAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientbyAgeActionPerformed(evt);
            }
        });
        SearchRecord.add(SearchPatientbyAge);

        jMenuBar2.add(SearchRecord);

        Helpmenu.setBackground(new java.awt.Color(204, 204, 204));
        Helpmenu.setText("Help menu");

        AboutUs.setText("About us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        Helpmenu.add(AboutUs);
        Helpmenu.add(jSeparator1);

        ChangePassword.setText("Change Password");
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });
        Helpmenu.add(ChangePassword);

        jMenuBar2.add(Helpmenu);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed

    }//GEN-LAST:event_AboutUsActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void SearchPatientbyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientbyIDActionPerformed
        cards.show(PanelContainer,"card3");
        SearchByIDField.requestFocus();
    }//GEN-LAST:event_SearchPatientbyIDActionPerformed

    private void SearchPatientbyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientbyNameActionPerformed
        cards.show(PanelContainer,"card2");
        SearchByNameField.requestFocus();
    }//GEN-LAST:event_SearchPatientbyNameActionPerformed

    private void SearchByNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByNameFieldActionPerformed
        String required = SearchByNameField.getText();
        searchPatientRecord("Patient_Name", required, SearchByNameTable);
        SearchByNameField.setText("");
        SearchByNameField.requestFocus();
    }//GEN-LAST:event_SearchByNameFieldActionPerformed

    private void SearchPatientByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientByNameButtonActionPerformed
        String required = SearchByNameField.getText();
        searchPatientRecord("Patient_Name", required, SearchByNameTable);
        SearchByNameField.setText("");
        SearchByNameField.requestFocus();
    }//GEN-LAST:event_SearchPatientByNameButtonActionPerformed

    private void SearchByIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByIDFieldActionPerformed
        String required = SearchByIDField.getText();
        searchPatientRecord("Patient_ID", required, SearchRecordByIDTable);
        SearchByIDField.setText("");
        SearchByIDField.requestFocus();
    }//GEN-LAST:event_SearchByIDFieldActionPerformed

    private void SearchRecordByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRecordByIDButtonActionPerformed
        String required = SearchByIDField.getText();
        searchPatientRecord("Patient_ID", required, SearchRecordByIDTable);
        SearchByIDField.setText("");
        SearchByIDField.requestFocus();
    }//GEN-LAST:event_SearchRecordByIDButtonActionPerformed

    private void notfoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notfoundButtonActionPerformed
        NotFoundPopUp.dispose();
    }//GEN-LAST:event_notfoundButtonActionPerformed

    private void SearchByAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByAgeFieldActionPerformed
        String required = SearchByAgeField.getText();
        searchPatientRecord("patient_age", required, SearchRecordByAgeTable);
        SearchByAgeField.setText("");
        SearchByAgeField.requestFocus();
    }//GEN-LAST:event_SearchByAgeFieldActionPerformed

    private void SearchRecordByAgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRecordByAgeButtonActionPerformed
        String required = SearchByAgeField.getText();
        searchPatientRecord("patient_age", required, SearchRecordByAgeTable);
        SearchByAgeField.setText("");
        SearchByAgeField.requestFocus();
    }//GEN-LAST:event_SearchRecordByAgeButtonActionPerformed

    private void SearchPatientbyAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientbyAgeActionPerformed
        cards.show(PanelContainer,"card4");
        SearchByAgeField.requestFocus();
    }//GEN-LAST:event_SearchPatientbyAgeActionPerformed

    private void SearchPatientRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientRecordButtonActionPerformed
        cards.show(PanelContainer,"card3");
        SearchByIDField.requestFocus();
    }//GEN-LAST:event_SearchPatientRecordButtonActionPerformed

    private void notfoundButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notfoundButtonKeyPressed
        NotFoundPopUp.dispose();
    }//GEN-LAST:event_notfoundButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUs;
    private javax.swing.JMenuItem ChangePassword;
    private javax.swing.JMenu Helpmenu;
    private MyButton LogOut;
    private javax.swing.JPanel LogOutButton;
    private javax.swing.JPanel MainScreen;
    private javax.swing.JDialog NotFoundPopUp;
    private javax.swing.JPanel PanelContainer;
    private MyButton PrintButton;
    private javax.swing.JTextField SearchByAgeField;
    private javax.swing.JTextField SearchByIDField;
    private javax.swing.JTextField SearchByNameField;
    private javax.swing.JLabel SearchByNameLabel;
    private javax.swing.JTable SearchByNameTable;
    private MyButton SearchPatientByNameButton;
    private MyButton SearchPatientRecordButton;
    private javax.swing.JMenuItem SearchPatientbyAge;
    private javax.swing.JMenuItem SearchPatientbyID;
    private javax.swing.JMenuItem SearchPatientbyName;
    private javax.swing.JMenu SearchRecord;
    private MyButton SearchRecordByAgeButton;
    private javax.swing.JLabel SearchRecordByAgeLabel;
    private javax.swing.JPanel SearchRecordByAgePanel;
    private javax.swing.JTable SearchRecordByAgeTable;
    private MyButton SearchRecordByIDButton;
    private javax.swing.JLabel SearchRecordByIDLabel;
    private javax.swing.JPanel SearchRecordByIDPanel;
    private javax.swing.JTable SearchRecordByIDTable;
    private javax.swing.JPanel SearchRecordByNamePanel;
    private javax.swing.JPanel ToolBarButtons;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton notfoundButton;
    // End of variables declaration//GEN-END:variables

    private void NotFound() {
        notfoundButton.requestFocus();
        NotFoundPopUp.setModal(true);
        NotFoundPopUp.setSize(400, 200);
        NotFoundPopUp.setLocationRelativeTo(null);
        NotFoundPopUp.setVisible(true);    
    }    

    private void searchPatientRecord(String tableColumn, String requiredItem, JTable outputTable) {
        try
        { 
            Connection conn = null;
            PreparedStatement  stmt = null;
            ResultSet rs = null;

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

            String DB = "Database\\Library System.accdb";
            String URL = "jdbc:ucanaccess://"+DB;

            conn = DriverManager.getConnection(URL);
            String query;
                        if (tableColumn.equals("patient_age")) {
                query = "SELECT Patient_ID, Patient_Name, PF_Name, Sex, DOB, Doctor_ID, Disease_History, Prescription," +
                        " DATEDIFF('yyyy', DOB, Date()) AS patient_age FROM Patient WHERE DATEDIFF('yyyy', DOB, Date()) = ?";
            } 
            else {
                query = "SELECT * FROM Patient WHERE " + tableColumn + "=?";
            }
            stmt = conn.prepareStatement(query);
            
             try
            {
                stmt.setString(1,requiredItem);
            }
            catch(Exception e)
            {
                throw new Exception("Please enter input in Numeric");
            }
             
            rs = stmt.executeQuery();
            
            int rowCount = 0;
            ResultSetMetaData rad = rs.getMetaData();
            int column = rad.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) outputTable.getModel();
            dft.setRowCount(0);
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
            
            while (rs.next()) {
                rowCount++;
                Vector section = new Vector();
                for(int i=0 ; i<column ; i++)
                {
                        section.add(rs.getString("Patient_ID"));
                        section.add(rs.getString("Patient_Name"));
                        section.add(rs.getString("PF_Name"));
                        section.add(rs.getString("Sex"));
                        section.add(dateFormat.format(rs.getDate("DOB")));
                        section.add(rs.getString("Doctor_ID"));
                        section.add(rs.getString("Disease_History"));
                        section.add(rs.getString("Prescription"));
                }
                dft.addRow(section);
            }
            
            outputTable.getColumnModel().getColumn(6).setCellRenderer(new TextAreaRenderer());
            outputTable.getColumnModel().getColumn(7).setCellRenderer(new TextAreaRenderer());
            
            if (rowCount == 0) {
                NotFound();
            }

            conn.close();
            rs.close();
            stmt.close();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } 
}


