/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.*;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.*;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setIconImage(new ImageIcon("src\\res\\patient.png").getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        VerifiedPopUp = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        Verifiedcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        VerifiedInfo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ErrorPopUpDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        ErrorIcon1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ErrorInfo1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        LoginButton = new MyButton();
        CancelButton = new MyButton();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        AuthenticationText = new javax.swing.JLabel();

        VerifiedPopUp.setTitle("Successfull");
        VerifiedPopUp.setAlwaysOnTop(true);
        VerifiedPopUp.setResizable(false);
        VerifiedPopUp.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        Verifiedcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/verified.png"))); // NOI18N
        jPanel3.add(Verifiedcon, new java.awt.GridBagConstraints());

        VerifiedPopUp.getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        VerifiedInfo.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        VerifiedInfo.setText("Login Successfull");
        jPanel4.add(VerifiedInfo, new java.awt.GridBagConstraints());

        jButton2.setText("OK");
        jButton2.setPreferredSize(new java.awt.Dimension(55, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(33, 0, 0, 9);
        jPanel4.add(jButton2, gridBagConstraints);

        VerifiedPopUp.getContentPane().add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        ErrorIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/error.png"))); // NOI18N
        jPanel6.add(ErrorIcon1, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        ErrorInfo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ErrorInfo1.setText("Login Failed");
        jPanel5.add(ErrorInfo1, new java.awt.GridBagConstraints());

        jButton3.setText("OK");
        jButton3.setPreferredSize(new java.awt.Dimension(55, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(33, 0, 0, 9);
        jPanel5.add(jButton3, gridBagConstraints);

        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);

        ErrorPopUpDialog.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(780, 550));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        Left.setBackground(new java.awt.Color(204, 204, 255));
        Left.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/login.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        Left.add(jLabel1, gridBagConstraints);

        getContentPane().add(Left);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setLayout(new java.awt.GridBagLayout());

        LoginButton.setText("Login");
        LoginButton.setBorderColor(new java.awt.Color(153, 153, 153));
        LoginButton.setColor(new java.awt.Color(204, 204, 255));
        LoginButton.setColorClick(new java.awt.Color(129, 117, 249));
        LoginButton.setColorOver(new java.awt.Color(153, 153, 255));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.setPreferredSize(new java.awt.Dimension(300, 35));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 36);
        Right.add(LoginButton, gridBagConstraints);

        CancelButton.setText("Cancel");
        CancelButton.setBorderColor(new java.awt.Color(153, 153, 153));
        CancelButton.setColor(new java.awt.Color(204, 204, 255));
        CancelButton.setColorClick(new java.awt.Color(129, 117, 249));
        CancelButton.setColorOver(new java.awt.Color(153, 153, 255));
        CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelButton.setPreferredSize(new java.awt.Dimension(300, 35));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 36);
        Right.add(CancelButton, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        usernameLabel.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 0);
        Right.add(usernameLabel, gridBagConstraints);

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernameField.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(32, 22, 0, 42);
        Right.add(usernameField, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        passwordLabel.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        Right.add(passwordLabel, gridBagConstraints);

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(200, 35));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 22, 0, 42);
        Right.add(passwordField, gridBagConstraints);

        AuthenticationText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        AuthenticationText.setText("Sign In");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 21, 12);
        Right.add(AuthenticationText, gridBagConstraints);

        getContentPane().add(Right);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String username = usernameField.getText();
        String password = String.valueOf(passwordField.getPassword());

        try
        {
            Connection conn = null;
            PreparedStatement stmt = null;
            ResultSet reslt = null;

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

            String DB = "Database\\Library System.accdb";
            String URL = "jdbc:ucanaccess://"+DB;

            conn = DriverManager.getConnection(URL);
            String query = "SELECT Book_Name, Year_of_publishing FROM Book_Infomation WHERE Book_Name=? AND Year_of_publishing=?";

            stmt = conn.prepareStatement(query);
            stmt.setString(1,username);
            stmt.setString(2,password);

            reslt = stmt.executeQuery();

            if(reslt.next())
            {
//                PopVerifier();
                this.dispose();
                AdminPanel adp = new AdminPanel();
                adp.setLocationRelativeTo(null);
                adp.setVisible(true);
            }

            else
            {
                PopError();
            }

        }
        catch(Exception e)
        {
            PopError();
        }// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed
    
    private void PopError()
    {
        ErrorPopUpDialog.setModal(true);
        ErrorPopUpDialog.setSize(400, 200);
        ErrorPopUpDialog.setLocationRelativeTo(null);
        ErrorPopUpDialog.setVisible(true);
    }
    
//    private void PopVerifier()
//    {
//        VerifiedPopUp.setSize(400, 200);
//        VerifiedPopUp.setLocationRelativeTo(null);
//        VerifiedPopUp.setVisible(true);
//    }
    
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
        Main main = new Main();
        main.setLocationRelativeTo(null);
        main.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VerifiedPopUp.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ErrorPopUpDialog.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        LoginButtonActionPerformed(evt);
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthenticationText;
    private MyButton CancelButton;
    private javax.swing.JLabel ErrorIcon1;
    private javax.swing.JLabel ErrorInfo1;
    private javax.swing.JDialog ErrorPopUpDialog;
    private javax.swing.JPanel Left;
    private MyButton LoginButton;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel VerifiedInfo;
    private javax.swing.JFrame VerifiedPopUp;
    private javax.swing.JLabel Verifiedcon;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
