
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        setIconImage(new ImageIcon("src\\res\\patient.png").getImage());
        initComponents();
        Admin.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Top = new javax.swing.JPanel();
        TopText = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        LeftPic = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Admin = new MyButton();
        Guest = new MyButton();
        AccountTypeText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paitent Management System");
        setPreferredSize(new java.awt.Dimension(580, 440));
        setResizable(false);

        Top.setBackground(new java.awt.Color(255, 255, 255));
        Top.setLayout(new java.awt.GridBagLayout());

        TopText.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        TopText.setText(" Patient Management System ");
        Top.add(TopText, new java.awt.GridBagConstraints());

        getContentPane().add(Top, java.awt.BorderLayout.PAGE_START);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setLayout(new java.awt.GridBagLayout());

        LeftPic.setBackground(new java.awt.Color(255, 255, 255));
        LeftPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/main22.png"))); // NOI18N
        Left.add(LeftPic, new java.awt.GridBagConstraints());

        getContentPane().add(Left, java.awt.BorderLayout.LINE_START);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setLayout(new java.awt.GridBagLayout());

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin.png"))); // NOI18N
        Admin.setBorderColor(new java.awt.Color(240, 240, 240));
        Admin.setColor(new java.awt.Color(255, 102, 102));
        Admin.setColorClick(new java.awt.Color(204, 204, 255));
        Admin.setColorOver(new java.awt.Color(255, 0, 51));
        Admin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdminFocusLost(evt);
            }
        });
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        Admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdminKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        Right.add(Admin, gridBagConstraints);

        Guest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/g821.png"))); // NOI18N
        Guest.setBorderColor(new java.awt.Color(0, 0, 0));
        Guest.setColor(new java.awt.Color(137, 243, 137));
        Guest.setColorClick(new java.awt.Color(204, 204, 255));
        Guest.setColorOver(new java.awt.Color(0, 204, 51));
        Guest.setPreferredSize(new java.awt.Dimension(113, 89));
        Guest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GuestFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GuestFocusLost(evt);
            }
        });
        Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestActionPerformed(evt);
            }
        });
        Guest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GuestKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
        Right.add(Guest, gridBagConstraints);

        AccountTypeText.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        AccountTypeText.setText("Choose Account Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        Right.add(AccountTypeText, gridBagConstraints);

        getContentPane().add(Right, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        this.dispose();
        Login log = new Login();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestActionPerformed
        this.dispose();
        GuestPanel gp = new GuestPanel();
        gp.setSize(900,700);
        gp.setLocationRelativeTo(null);
        gp.setVisible(true);
    }//GEN-LAST:event_GuestActionPerformed

    private void AdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminKeyPressed
        this.dispose();
        Login log = new Login();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
    }//GEN-LAST:event_AdminKeyPressed

    private void AdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminFocusGained
//         Admin.setColor(new java.awt.Color(255, 0, 51));
        Admin.setBorderColor(new Color(0,0,0));
    }//GEN-LAST:event_AdminFocusGained

    private void AdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminFocusLost
//        Admin.setColor(new java.awt.Color(255,153,153));
        Admin.setBorderColor(new Color(255,102,102));
    }//GEN-LAST:event_AdminFocusLost

    private void GuestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GuestKeyPressed
        this.dispose();
        GuestPanel gp = new GuestPanel();
        gp.setSize(900,700);
        gp.setLocationRelativeTo(null);
        gp.setVisible(true);
    }//GEN-LAST:event_GuestKeyPressed

    private void GuestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GuestFocusGained
//        Guest.setColor(new java.awt.Color(0,204,51));
        Guest.setBorderColor(new Color(0,0,0));
    }//GEN-LAST:event_GuestFocusGained

    private void GuestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GuestFocusLost
//        Guest.setColor(new java.awt.Color(204,255,204));
        Guest.setBorderColor(new Color(137,243,137));
    }//GEN-LAST:event_GuestFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setLocationRelativeTo(null);
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountTypeText;
    private MyButton Admin;
    private MyButton Guest;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel LeftPic;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Top;
    private javax.swing.JLabel TopText;
    // End of variables declaration//GEN-END:variables
}
